name: gkp_qchard
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py314hca03da5_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=2.0.1=py314hca03da5_0
  - cairo=1.18.4=h191e429_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h20e30b6_0
  - cpython=3.14.2=py314hd8ed1ab_100
  - cycler=0.12.1=py314hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py314h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.1=pyhcf101f3_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py314haa24f5a_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - gettext=0.21.0=hbdbcc25_2
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.2=py314hbcc4bda_0
  - graphite2=1.3.14=hc377ac9_1
  - h5py=3.15.1=nompi_py314h1c8d760_101
  - harfbuzz=12.3.0=h9837a22_1
  - hdf5=1.14.6=nompi_h51e7c0a_105
  - icu=73.1=h313beb8_0
  - iniconfig=2.3.0=py314hca03da5_0
  - ipykernel=6.31.0=py314h7136c26_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipyvue=1.11.2=pyhd8ed1ab_0
  - ipyvuetify=1.11.3=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.8.0=py314hca03da5_0
  - jupyter_core=5.9.1=py314hca03da5_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py314haeee614_0
  - krb5=1.22.1=h88776f3_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libaec=1.1.4=h51d1e36_0
  - libavif=1.3.0=h839b4eb_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.8=py314hca03da5_0
  - matplotlib-base=3.10.8=py314haeb1505_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - matplotlib-label-lines=0.7.0=pyhd8ed1ab_1
  - more-itertools=10.8.0=pyhcf101f3_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multiprocess=0.70.18=py314h9d33bd4_2
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numpy=2.4.1=py314hde9b8b7_0
  - numpy-base=2.4.1=py314hb4b2851_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=py314hca03da5_1
  - parso=0.8.5=pyhcf101f3_0
  - pathos=0.3.4=pyhd8ed1ab_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py314h7b5562e_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py314hca03da5_0
  - pluggy=1.5.0=py314hca03da5_0
  - pox=0.3.7=pyhcf101f3_0
  - ppft=1.7.8=pyhcf101f3_1
  - prompt-toolkit=3.0.52=py314hca03da5_1
  - psutil=7.0.0=py314haa24f5a_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=py314hca03da5_0
  - pyparsing=3.2.5=py314hca03da5_0
  - pytest=8.4.2=py314hca03da5_0
  - python=3.14.2=h1858270_101_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python_abi=3.14=2_cp314
  - pyzmq=27.1.0=py314h5a8c52c_1
  - qutip=5.2.2=py314h95ce61a_0
  - readline=8.3=h0b18652_0
  - scipy=1.17.0=py314hfc1f868_1
  - scqubits=4.3.1=pyhd8ed1ab_0
  - setuptools=80.10.1=pyh332efcf_0
  - six=1.17.0=py314hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py314haa24f5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - qutip-qip==0.4.1
prefix: /Users/thomasersevim/anaconda3/envs/gkp_qchard
